#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("mhartl-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
let palindromesDetected = [];
text.split("\n").forEach((line) => {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    palindromesDetected.push(line);
  }
});
fs.writeFileSync("palindromes.txt", palindromesDetected.join("\n") + "\n", "utf-8");